package org.asmeta.asm2java.asm.monitored;

public class MonitoredGetter {
  public static void monitoredGetter(final /* Asm */Object asm, final /* StringBuffer */Object sb) {
    throw new Error("Unresolved compilation problems:"
      + "\nMonitoredFunction cannot be resolved to a type."
      + "\nConcreteDomain cannot be resolved to a type."
      + "\nConcreteDomain cannot be resolved to a type."
      + "\nConcreteDomain cannot be resolved to a type."
      + "\nConcreteDomain cannot be resolved to a type."
      + "\nEnumTd cannot be resolved to a type."
      + "\nAbstractTd cannot be resolved to a type."
      + "\nEnumTd cannot be resolved to a type."
      + "\nConcreteDomain cannot be resolved to a type."
      + "\nAbstractTd cannot be resolved to a type."
      + "\nStaticFunction cannot be resolved to a type."
      + "\nConcreteDomain cannot be resolved to a type."
      + "\n! cannot be resolved."
      + "\n! cannot be resolved."
      + "\n! cannot be resolved."
      + "\n|| cannot be resolved."
      + "\n< cannot be resolved."
      + "\nToString cannot be resolved."
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\n++ cannot be resolved."
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nUnreachable code: The if condition can never match. It is already handled by a previous condition."
      + "\nname cannot be resolved"
      + "\nheaderSection cannot be resolved"
      + "\nsignature cannot be resolved"
      + "\nfunction cannot be resolved"
      + "\ndomain cannot be resolved"
      + "\n=== cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nequals cannot be resolved"
      + "\n&& cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\nname cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nequals cannot be resolved"
      + "\n&& cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\nname cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nequals cannot be resolved"
      + "\n&& cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\nname cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\nname cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nappend cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nname cannot be resolved"
      + "\nname cannot be resolved"
      + "\nheaderSection cannot be resolved"
      + "\nsignature cannot be resolved"
      + "\ndomain cannot be resolved"
      + "\nequals cannot be resolved"
      + "\ndomain cannot be resolved"
      + "\nelement cannot be resolved"
      + "\nsize cannot be resolved"
      + "\nvisit cannot be resolved"
      + "\nelement cannot be resolved"
      + "\nget cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\ndomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nname cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\ndomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nheaderSection cannot be resolved"
      + "\nsignature cannot be resolved"
      + "\nfunction cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nequals cannot be resolved"
      + "\n&& cannot be resolved"
      + "\ndomain cannot be resolved"
      + "\n=== cannot be resolved"
      + "\nname cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\ndomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\ndomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nname cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\ndomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\ndomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved");
  }
}
