package org.asmeta.asm2java.asm.controlled;

public class PrintControlled {
  public static Object printControlled(final /* Asm */Object asm) {
    throw new Error("Unresolved compilation problems:"
      + "\nAbstractTd cannot be resolved to a type."
      + "\nControlledFunction cannot be resolved to a type."
      + "\nConcreteDomain cannot be resolved to a type."
      + "\nMapDomain cannot be resolved to a type."
      + "\nSequenceDomain cannot be resolved to a type."
      + "\nEnumTd cannot be resolved to a type."
      + "\nEnumTd cannot be resolved to a type."
      + "\nConcreteDomain cannot be resolved to a type."
      + "\nEnumTd cannot be resolved to a type."
      + "\nEnumTd cannot be resolved to a type."
      + "\nStringBuffer cannot be resolved."
      + "\n&& cannot be resolved."
      + "\n&& cannot be resolved."
      + "\nheaderSection cannot be resolved"
      + "\nsignature cannot be resolved"
      + "\ndomain cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\nname cannot be resolved"
      + "\nname cannot be resolved"
      + "\nname cannot be resolved"
      + "\nname cannot be resolved"
      + "\nheaderSection cannot be resolved"
      + "\nsignature cannot be resolved"
      + "\nfunction cannot be resolved"
      + "\ndomain cannot be resolved"
      + "\n=== cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\nname cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nequals cannot be resolved"
      + "\n|| cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nequals cannot be resolved"
      + "\n|| cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\nname cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\nname cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\nname cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\nname cannot be resolved"
      + "\ndomain cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nappend cannot be resolved"
      + "\ndomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nname cannot be resolved"
      + "\ndomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nname cannot be resolved"
      + "\ndomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\ndomain cannot be resolved"
      + "\ncodomain cannot be resolved"
      + "\nappend cannot be resolved"
      + "\ndomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nname cannot be resolved"
      + "\ndomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\nname cannot be resolved"
      + "\ndomain cannot be resolved"
      + "\nname cannot be resolved"
      + "\ntoString cannot be resolved");
  }
}
