package org.asmeta.asm2java.asm.cover;

public class FinalState {
  public static Object ifFinalState(final /* Asm */Object asm, final /* StringBuffer */Object sb, final Object/* type is 'null' */ finalStateConditions) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\n!== cannot be resolved"
      + "\n&& cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\n! cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved");
  }

  public static Object setIsFinalState(final /* Asm */Object asm, final /* StringBuffer */Object sb, final Object/* type is 'null' */ finalStateConditions) {
    throw new Error("Unresolved compilation problems:"
      + "\nControlledFunction cannot be resolved to a type."
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nStringBuffer cannot be resolved."
      + "\n+= cannot be resolved."
      + "\nThe method or field System is undefined"
      + "\n+= cannot be resolved."
      + "\n&& cannot be resolved."
      + "\nThe method or field System is undefined"
      + "\n+= cannot be resolved."
      + "\n== cannot be resolved."
      + "\nThe method or field System is undefined"
      + "\n== cannot be resolved."
      + "\nThe method or field System is undefined"
      + "\n- cannot be resolved."
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\n!== cannot be resolved"
      + "\n&& cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\n! cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nreplaceAll cannot be resolved"
      + "\nreplaceAll cannot be resolved"
      + "\ntoLowerCase cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nmatches cannot be resolved"
      + "\n! cannot be resolved"
      + "\nreplaceAll cannot be resolved"
      + "\nname cannot be resolved"
      + "\nreplaceAll cannot be resolved"
      + "\nconcat cannot be resolved"
      + "\nheaderSection cannot be resolved"
      + "\nsignature cannot be resolved"
      + "\nfunction cannot be resolved"
      + "\nname cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nname cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\ntoString cannot be resolved"
      + "\nsetLength cannot be resolved"
      + "\nlength cannot be resolved"
      + "\n- cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\ntoString cannot be resolved"
      + "\nsetLength cannot be resolved"
      + "\nlength cannot be resolved"
      + "\n- cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved");
  }
}
