package org.asmeta.asm2java.asm.main;

public class JavaASMGenerator /* implements AsmToJavaGenerator  */{
  public java.lang.Object compileAndWrite(final /* Asm */Object asm, final /* String */Object writerPath, final /* TranslatorOptions */Object userOptions) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Assert is undefined"
      + "\nInvalid number of arguments. The method compileAndWrite(Asm, String, TranslatorOptions) is not applicable for the arguments (Asm,String,java.lang.String,TranslatorOptions)"
      + "\nThe method compileAndWrite(Asm, String, TranslatorOptions) from the type JavaASMGenerator refers to the missing type java.lang.Object"
      + "\nassertTrue cannot be resolved"
      + "\nendsWith cannot be resolved");
  }

  private /* List<Rule> */Object seqCalledRules;

  private Object/* type is 'null' */ finalStateConditions;

  public Object/* type is 'null' */ setFinalStateConditions(final Object/* type is 'null' */ finalStateConditions) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field JavaASMGenerator.finalStateConditions refers to the missing type String");
  }

  public Object compileAsm(final /* Asm */Object asm) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field options is undefined"
      + "\nArrayList cannot be resolved."
      + "\nSeqRuleCollector cannot be resolved."
      + "\nStringBuffer cannot be resolved."
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe method or field System is undefined"
      + "\nThe field JavaASMGenerator.seqCalledRules refers to the missing type // all the rules that must translate in two versions seq and not seq\r\n\t// if null, translate all\r\n\tList"
      + "\nThe field JavaASMGenerator.seqCalledRules refers to the missing type // all the rules that must translate in two versions seq and not seq\r\n\t// if null, translate all\r\n\tList"
      + "\nThe field JavaASMGenerator.finalStateConditions refers to the missing type String"
      + "\nThe field JavaASMGenerator.finalStateConditions refers to the missing type String"
      + "\noptimizeSeqMacroRule cannot be resolved"
      + "\nbodySection cannot be resolved"
      + "\nruleDeclaration cannot be resolved"
      + "\naddAll cannot be resolved"
      + "\nvisit cannot be resolved"
      + "\nname cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nsetMonitoredArgsFunc cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nsetMonitoredArgsMet cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nifFinalState cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nsetIsFinalState cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nmonitoredGetter cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\ncontrolledGetter cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\ncoverFunctions cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\ncoverFunctions cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nlineSeparator cannot be resolved"
      + "\ncoverBranches cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nprintControlled cannot be resolved"
      + "\nsetMonitoredArgsFunc cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nsetMonitored cannot be resolved"
      + "\ntoString cannot be resolved");
  }
}
