name: Docker Image CI

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'}}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-asmetal2java_asmgen-jar
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./asmetal2java_asmgen
          dockerfile: ./asmetal2java_asmgen/Dockerfile 
          push: true
          tags: isaacmaffeis/asmetal2java:latest
      
      - name: Delete Artifact
        uses: GeekyEggo/delete-artifact@v5.1.0
        with:
          name: artifact-asmetal2java_asmgen-jar
