name: Build and Push CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn --batch-mode clean install

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: asmetal2java_asmgen-0.0.1-SNAPSHOT-jar-with-dependencies.jar
          path: asmetal2java_asmgen/target/asmetal2java_asmgen-0.0.1-SNAPSHOT-jar-with-dependencies.jar
          retention-days: 1

  docker:
    name: Push Docker Image
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: asmetal2java_asmgen-0.0.1-SNAPSHOT-jar-with-dependencies.jar
          path: ./asmetal2java_asmgen/target

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./asmetal2java_asmgen
          dockerfile: ./asmetal2java_asmgen/Dockerfile
          push: true
          tags: isaacmaffeis/asmetal2java:latest

      - name: Delete Artifact
        uses: GeekyEggo/delete-artifact@v5.1.0
        with:
          name: asmetal2java_asmgen-0.0.1-SNAPSHOT-jar-with-dependencies.jar
